# image will be published to ghcr.io/<user>/<name>
name: davidos

description: my ready-to-go OS 

base-image: ghcr.io/ublue-os/silverblue-main

# latest is also supported if you want new updates ASAP
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo

    install:
      - powertop
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-dash-to-dock
      - gnome-themes-extra
      - distrobox
      - tailscale
      - podman-compose
      - hdparm
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - samba
      - sway-config-fedora
    remove:
      - toolbox
      - firefox
      - firefox-langpacks
      - gnome-tour

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.brave.Browser
        - org.gnome.TextEditor
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.clocks
        - org.gnome.Contacts
        - org.gnome.baobab
        - org.gnome.Evince
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Weather
        - com.bitwarden.desktop
        - org.libreoffice.LibreOffice
        - com.borgbase.Vorta
        - io.beekeeperstudio.Studio
        - md.obsidian.Obsidian
        - com.valvesoftware.Steam
        - org.videolan.VLC
        - io.bassi.Amberol
        - io.podman_desktop.PodmanDesktop
        - org.qbittorrent.qBittorrent
        - org.zotero.Zotero
        - com.github.qarmin.czkawka

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - SourceCodePro
      google-fonts:
        - Roboto
        - Open Sans

  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - smb.service
        - davidos-groups.service
        - docker.socket

  - type: script
    scripts:
      - install-insync.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: gschema-overrides
    include:
      - zz1-myoverride.gschema.override # test & compile the override file included in config/gschema-overrides/zz1-myoverride.gschema.override
