# image will be published to ghcr.io/<user>/<name>
name: davidOS

description: my ready-to-go OS

base-image: ghcr.io/ublue-os/silverblue-main

# latest is also supported if you want new updates ASAP
image-version: 39

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo

    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-dash-to-dock
      - gnome-themes-extra
      - distrobox
      - tailscale
      - podman-compose
      - code
      - hdparm
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - samba
    remove:
      - toolbox
      - firefox
      - firefox-langpacks
      - gnome-tour

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.clocks
        - org.gnome.Contacts
        - org.gnome.baobab
        - org.gnome.Evince
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Weather
        - com.bitwarden.desktop
        - org.libreoffice.LibreOffice
        - com.borgbase.Vorta
        - io.beekeeperstudio.Studio
        - md.obsidian.Obsidian
        - com.valvesoftware.Steam
        - org.videolan.VLC
        - io.bassi.Amberol
        - io.podman_desktop.PodmanDesktop
        - sh.cider.Cider
        - org.qbittorrent.qBittorrent
        - org.zotero.Zotero

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
      google-fonts:
        - Roboto
        - Open Sans

  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - smb.service
        - davidos-groups.service
        - docker.socket

  - type: script
    scripts:
      - install-prompt.sh
      - install-insync.sh
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
