# image will be published to ghcr.io/<user>/<name>
name: dos

description: dos = david's os

base-image: ghcr.io/ublue-os/silverblue-main

# latest is also supported if you want new updates ASAP
image-version: 39

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: rpm-ostree
    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-themes-extra
      - distrobox
      - tailscale
      - insync
      - podman-compose
    remove:
      - toolbox
      - firefox
      - firefox-langpacks
      - gnome-tour

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.clocks
        - org.gnome.Contacts
        - org.gnome.baobab
        - org.gnome.Evince
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Weather
        - com.bitwarden.desktop
        - com.brave.Browser
        - org.libreoffice.LibreOffice
        - com.borgbase.Vorta
        - io.beekeeperstudio.Studio
        - md.obsidian.Obsidian
        - com.valvesoftware.Steam
        - org.videolan.VLC
        - io.bassi.Amberol
        - com.visualstudio.code
        - io.podman_desktop.PodmanDesktop

  - type: bling
    install:
      - justfiles
      - ublue-update
      - dconf-update-service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
      google-fonts:
        - Roboto
        - Open Sans

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
